/* Generated By:JavaCC: Do not edit this line. Prism3To4Constants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Prism3To4Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int COMMENT = 2;
  /** RegularExpression Id. */
  int BOOL = 3;
  /** RegularExpression Id. */
  int CONST = 4;
  /** RegularExpression Id. */
  int CEIL = 5;
  /** RegularExpression Id. */
  int CTMC = 6;
  /** RegularExpression Id. */
  int CUMUL = 7;
  /** RegularExpression Id. */
  int DISTRIBUTION = 8;
  /** RegularExpression Id. */
  int DIRAC = 9;
  /** RegularExpression Id. */
  int DOUBLE = 10;
  /** RegularExpression Id. */
  int DTMC = 11;
  /** RegularExpression Id. */
  int ENDINIT = 12;
  /** RegularExpression Id. */
  int ENDMODULE = 13;
  /** RegularExpression Id. */
  int ENDREWARDS = 14;
  /** RegularExpression Id. */
  int ENDSYSTEM = 15;
  /** RegularExpression Id. */
  int EVENT = 16;
  /** RegularExpression Id. */
  int EXPONENTIAL = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int FLOOR = 19;
  /** RegularExpression Id. */
  int FORMULA = 20;
  /** RegularExpression Id. */
  int FUNC = 21;
  /** RegularExpression Id. */
  int FUTURE = 22;
  /** RegularExpression Id. */
  int GLOBAL = 23;
  /** RegularExpression Id. */
  int GLOB = 24;
  /** RegularExpression Id. */
  int GSMP = 25;
  /** RegularExpression Id. */
  int INIT = 26;
  /** RegularExpression Id. */
  int INST = 27;
  /** RegularExpression Id. */
  int INT = 28;
  /** RegularExpression Id. */
  int LABEL = 29;
  /** RegularExpression Id. */
  int MAX = 30;
  /** RegularExpression Id. */
  int MDP = 31;
  /** RegularExpression Id. */
  int MIN = 32;
  /** RegularExpression Id. */
  int MODULE = 33;
  /** RegularExpression Id. */
  int NEXT = 34;
  /** RegularExpression Id. */
  int NONDETERMINISTIC = 35;
  /** RegularExpression Id. */
  int PMAX = 36;
  /** RegularExpression Id. */
  int PMIN = 37;
  /** RegularExpression Id. */
  int P = 38;
  /** RegularExpression Id. */
  int PROBABILISTIC = 39;
  /** RegularExpression Id. */
  int PROB = 40;
  /** RegularExpression Id. */
  int RATE = 41;
  /** RegularExpression Id. */
  int REWARDS = 42;
  /** RegularExpression Id. */
  int RMAX = 43;
  /** RegularExpression Id. */
  int RMIN = 44;
  /** RegularExpression Id. */
  int R = 45;
  /** RegularExpression Id. */
  int S = 46;
  /** RegularExpression Id. */
  int STOCHASTIC = 47;
  /** RegularExpression Id. */
  int SYSTEM = 48;
  /** RegularExpression Id. */
  int TRUE = 49;
  /** RegularExpression Id. */
  int UNIFORM = 50;
  /** RegularExpression Id. */
  int UNTIL = 51;
  /** RegularExpression Id. */
  int WEIBULL = 52;
  /** RegularExpression Id. */
  int NOT = 53;
  /** RegularExpression Id. */
  int AND = 54;
  /** RegularExpression Id. */
  int OR = 55;
  /** RegularExpression Id. */
  int IMPLIES = 56;
  /** RegularExpression Id. */
  int RARROW = 57;
  /** RegularExpression Id. */
  int COLON = 58;
  /** RegularExpression Id. */
  int SEMICOLON = 59;
  /** RegularExpression Id. */
  int COMMA = 60;
  /** RegularExpression Id. */
  int DOTS = 61;
  /** RegularExpression Id. */
  int LPARENTH = 62;
  /** RegularExpression Id. */
  int RPARENTH = 63;
  /** RegularExpression Id. */
  int LBRACKET = 64;
  /** RegularExpression Id. */
  int RBRACKET = 65;
  /** RegularExpression Id. */
  int LBRACE = 66;
  /** RegularExpression Id. */
  int RBRACE = 67;
  /** RegularExpression Id. */
  int EQ = 68;
  /** RegularExpression Id. */
  int NE = 69;
  /** RegularExpression Id. */
  int LT = 70;
  /** RegularExpression Id. */
  int GT = 71;
  /** RegularExpression Id. */
  int LE = 72;
  /** RegularExpression Id. */
  int GE = 73;
  /** RegularExpression Id. */
  int PLUS = 74;
  /** RegularExpression Id. */
  int MINUS = 75;
  /** RegularExpression Id. */
  int TIMES = 76;
  /** RegularExpression Id. */
  int DIVIDE = 77;
  /** RegularExpression Id. */
  int PRIME = 78;
  /** RegularExpression Id. */
  int RENAME = 79;
  /** RegularExpression Id. */
  int QMARK = 80;
  /** RegularExpression Id. */
  int DQUOTE = 81;
  /** RegularExpression Id. */
  int REG_INT = 82;
  /** RegularExpression Id. */
  int REG_DOUBLE = 83;
  /** RegularExpression Id. */
  int REG_IDENTPRIME = 84;
  /** RegularExpression Id. */
  int REG_IDENT = 85;
  /** RegularExpression Id. */
  int PREPROC = 86;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<COMMENT>",
    "\"bool\"",
    "\"const\"",
    "\"ceil\"",
    "\"ctmc\"",
    "\"C\"",
    "\"distribution\"",
    "\"dirac\"",
    "\"double\"",
    "\"dtmc\"",
    "\"endinit\"",
    "\"endmodule\"",
    "\"endrewards\"",
    "\"endsystem\"",
    "\"event\"",
    "\"exponential\"",
    "\"false\"",
    "\"floor\"",
    "\"formula\"",
    "\"func\"",
    "\"F\"",
    "\"global\"",
    "\"G\"",
    "\"gsmp\"",
    "\"init\"",
    "\"I\"",
    "\"int\"",
    "\"label\"",
    "\"max\"",
    "\"mdp\"",
    "\"min\"",
    "\"module\"",
    "\"X\"",
    "\"nondeterministic\"",
    "\"Pmax\"",
    "\"Pmin\"",
    "\"P\"",
    "\"probabilistic\"",
    "\"prob\"",
    "\"rate\"",
    "\"rewards\"",
    "\"Rmax\"",
    "\"Rmin\"",
    "\"R\"",
    "\"S\"",
    "\"stochastic\"",
    "\"system\"",
    "\"true\"",
    "\"uniform\"",
    "\"U\"",
    "\"weibull\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"=>\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"..\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "\"<-\"",
    "\"?\"",
    "\"\\\"\"",
    "<REG_INT>",
    "<REG_DOUBLE>",
    "<REG_IDENTPRIME>",
    "<REG_IDENT>",
    "<PREPROC>",
  };

}
