/* Generated By:JavaCC: Do not edit this line. PrismParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PrismParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int COMMENT = 2;
  /** RegularExpression Id. */
  int A = 3;
  /** RegularExpression Id. */
  int BOOL = 4;
  /** RegularExpression Id. */
  int CLOCK = 5;
  /** RegularExpression Id. */
  int CONST = 6;
  /** RegularExpression Id. */
  int CTMC = 7;
  /** RegularExpression Id. */
  int C = 8;
  /** RegularExpression Id. */
  int DISTRIBUTION = 9;
  /** RegularExpression Id. */
  int DIRAC = 10;
  /** RegularExpression Id. */
  int DOUBLE = 11;
  /** RegularExpression Id. */
  int DTMC = 12;
  /** RegularExpression Id. */
  int E = 13;
  /** RegularExpression Id. */
  int ENDINIT = 14;
  /** RegularExpression Id. */
  int ENDINVARIANT = 15;
  /** RegularExpression Id. */
  int ENDMODULE = 16;
  /** RegularExpression Id. */
  int ENDREWARDS = 17;
  /** RegularExpression Id. */
  int ENDSYSTEM = 18;
  /** RegularExpression Id. */
  int EVENT = 19;
  /** RegularExpression Id. */
  int EXPONENTIAL = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int FORMULA = 22;
  /** RegularExpression Id. */
  int FILTER = 23;
  /** RegularExpression Id. */
  int FUNC = 24;
  /** RegularExpression Id. */
  int F = 25;
  /** RegularExpression Id. */
  int GLOBAL = 26;
  /** RegularExpression Id. */
  int G = 27;
  /** RegularExpression Id. */
  int INIT = 28;
  /** RegularExpression Id. */
  int GSMP = 29;
  /** RegularExpression Id. */
  int INVARIANT = 30;
  /** RegularExpression Id. */
  int I = 31;
  /** RegularExpression Id. */
  int INT = 32;
  /** RegularExpression Id. */
  int LABEL = 33;
  /** RegularExpression Id. */
  int MAX = 34;
  /** RegularExpression Id. */
  int MDP = 35;
  /** RegularExpression Id. */
  int MIN = 36;
  /** RegularExpression Id. */
  int MODULE = 37;
  /** RegularExpression Id. */
  int X = 38;
  /** RegularExpression Id. */
  int NONDETERMINISTIC = 39;
  /** RegularExpression Id. */
  int PMAX = 40;
  /** RegularExpression Id. */
  int PMIN = 41;
  /** RegularExpression Id. */
  int P = 42;
  /** RegularExpression Id. */
  int PROBABILISTIC = 43;
  /** RegularExpression Id. */
  int PROB = 44;
  /** RegularExpression Id. */
  int PTA = 45;
  /** RegularExpression Id. */
  int RATE = 46;
  /** RegularExpression Id. */
  int REWARDS = 47;
  /** RegularExpression Id. */
  int RMAX = 48;
  /** RegularExpression Id. */
  int RMIN = 49;
  /** RegularExpression Id. */
  int R = 50;
  /** RegularExpression Id. */
  int S = 51;
  /** RegularExpression Id. */
  int STOCHASTIC = 52;
  /** RegularExpression Id. */
  int SYSTEM = 53;
  /** RegularExpression Id. */
  int TRUE = 54;
  /** RegularExpression Id. */
  int U = 55;
  /** RegularExpression Id. */
  int UNIFORM = 56;
  /** RegularExpression Id. */
  int W = 57;
  /** RegularExpression Id. */
  int WEIBULL = 58;
  /** RegularExpression Id. */
  int NOT = 59;
  /** RegularExpression Id. */
  int AND = 60;
  /** RegularExpression Id. */
  int OR = 61;
  /** RegularExpression Id. */
  int IMPLIES = 62;
  /** RegularExpression Id. */
  int IFF = 63;
  /** RegularExpression Id. */
  int RARROW = 64;
  /** RegularExpression Id. */
  int COLON = 65;
  /** RegularExpression Id. */
  int SEMICOLON = 66;
  /** RegularExpression Id. */
  int COMMA = 67;
  /** RegularExpression Id. */
  int DOTS = 68;
  /** RegularExpression Id. */
  int LPARENTH = 69;
  /** RegularExpression Id. */
  int RPARENTH = 70;
  /** RegularExpression Id. */
  int LBRACKET = 71;
  /** RegularExpression Id. */
  int RBRACKET = 72;
  /** RegularExpression Id. */
  int DLBRACKET = 73;
  /** RegularExpression Id. */
  int DRBRACKET = 74;
  /** RegularExpression Id. */
  int LBRACE = 75;
  /** RegularExpression Id. */
  int RBRACE = 76;
  /** RegularExpression Id. */
  int EQ = 77;
  /** RegularExpression Id. */
  int NE = 78;
  /** RegularExpression Id. */
  int LT = 79;
  /** RegularExpression Id. */
  int GT = 80;
  /** RegularExpression Id. */
  int DLT = 81;
  /** RegularExpression Id. */
  int DGT = 82;
  /** RegularExpression Id. */
  int LE = 83;
  /** RegularExpression Id. */
  int GE = 84;
  /** RegularExpression Id. */
  int PLUS = 85;
  /** RegularExpression Id. */
  int MINUS = 86;
  /** RegularExpression Id. */
  int TIMES = 87;
  /** RegularExpression Id. */
  int DIVIDE = 88;
  /** RegularExpression Id. */
  int PRIME = 89;
  /** RegularExpression Id. */
  int RENAME = 90;
  /** RegularExpression Id. */
  int QMARK = 91;
  /** RegularExpression Id. */
  int DQUOTE = 92;
  /** RegularExpression Id. */
  int REG_INT = 93;
  /** RegularExpression Id. */
  int REG_DOUBLE = 94;
  /** RegularExpression Id. */
  int REG_IDENTPRIME = 95;
  /** RegularExpression Id. */
  int REG_IDENT = 96;
  /** RegularExpression Id. */
  int PREPROC = 97;
  /** RegularExpression Id. */
  int LEXICAL_ERROR = 98;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<COMMENT>",
    "\"A\"",
    "\"bool\"",
    "\"clock\"",
    "\"const\"",
    "\"ctmc\"",
    "\"C\"",
    "\"distribution\"",
    "\"dirac\"",
    "\"double\"",
    "\"dtmc\"",
    "\"E\"",
    "\"endinit\"",
    "\"endinvariant\"",
    "\"endmodule\"",
    "\"endrewards\"",
    "\"endsystem\"",
    "\"event\"",
    "\"exponential\"",
    "\"false\"",
    "\"formula\"",
    "\"filter\"",
    "\"func\"",
    "\"F\"",
    "\"global\"",
    "\"G\"",
    "\"init\"",
    "\"gsmp\"",
    "\"invariant\"",
    "\"I\"",
    "\"int\"",
    "\"label\"",
    "\"max\"",
    "\"mdp\"",
    "\"min\"",
    "\"module\"",
    "\"X\"",
    "\"nondeterministic\"",
    "\"Pmax\"",
    "\"Pmin\"",
    "\"P\"",
    "\"probabilistic\"",
    "\"prob\"",
    "\"pta\"",
    "\"rate\"",
    "\"rewards\"",
    "\"Rmax\"",
    "\"Rmin\"",
    "\"R\"",
    "\"S\"",
    "\"stochastic\"",
    "\"system\"",
    "\"true\"",
    "\"U\"",
    "\"uniform\"",
    "\"W\"",
    "\"weibull\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"=>\"",
    "\"<=>\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"..\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"[[\"",
    "\"]]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<<\"",
    "\">>\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "\"<-\"",
    "\"?\"",
    "\"\\\"\"",
    "<REG_INT>",
    "<REG_DOUBLE>",
    "<REG_IDENTPRIME>",
    "<REG_IDENT>",
    "<PREPROC>",
    "<LEXICAL_ERROR>",
  };

}
