/* Generated By:JavaCC: Do not edit this line. PrismParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PrismParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int COMMENT = 2;
  /** RegularExpression Id. */
  int A = 3;
  /** RegularExpression Id. */
  int BOOL = 4;
  /** RegularExpression Id. */
  int CLOCK = 5;
  /** RegularExpression Id. */
  int CONST = 6;
  /** RegularExpression Id. */
  int CTMC = 7;
  /** RegularExpression Id. */
  int C = 8;
  /** RegularExpression Id. */
  int DISTRIBUTION = 9;
  /** RegularExpression Id. */
  int DIRAC = 10;
  /** RegularExpression Id. */
  int DOUBLE = 11;
  /** RegularExpression Id. */
  int DTMC = 12;
  /** RegularExpression Id. */
  int E = 13;
  /** RegularExpression Id. */
  int ENDINIT = 14;
  /** RegularExpression Id. */
  int ENDINVARIANT = 15;
  /** RegularExpression Id. */
  int ENDMODULE = 16;
  /** RegularExpression Id. */
  int ENDREWARDS = 17;
  /** RegularExpression Id. */
  int ENDSYSTEM = 18;
  /** RegularExpression Id. */
  int ERLANG = 19;
  /** RegularExpression Id. */
  int EVENT = 20;
  /** RegularExpression Id. */
  int EXPONENTIAL = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int FORMULA = 23;
  /** RegularExpression Id. */
  int FILTER = 24;
  /** RegularExpression Id. */
  int FUNC = 25;
  /** RegularExpression Id. */
  int F = 26;
  /** RegularExpression Id. */
  int GLOBAL = 27;
  /** RegularExpression Id. */
  int G = 28;
  /** RegularExpression Id. */
  int INIT = 29;
  /** RegularExpression Id. */
  int GSMP = 30;
  /** RegularExpression Id. */
  int INVARIANT = 31;
  /** RegularExpression Id. */
  int I = 32;
  /** RegularExpression Id. */
  int INT = 33;
  /** RegularExpression Id. */
  int LABEL = 34;
  /** RegularExpression Id. */
  int MAX = 35;
  /** RegularExpression Id. */
  int MDP = 36;
  /** RegularExpression Id. */
  int MIN = 37;
  /** RegularExpression Id. */
  int MODULE = 38;
  /** RegularExpression Id. */
  int X = 39;
  /** RegularExpression Id. */
  int NONDETERMINISTIC = 40;
  /** RegularExpression Id. */
  int PMAX = 41;
  /** RegularExpression Id. */
  int PMIN = 42;
  /** RegularExpression Id. */
  int P = 43;
  /** RegularExpression Id. */
  int PROBABILISTIC = 44;
  /** RegularExpression Id. */
  int PROB = 45;
  /** RegularExpression Id. */
  int PTA = 46;
  /** RegularExpression Id. */
  int RATE = 47;
  /** RegularExpression Id. */
  int REWARDS = 48;
  /** RegularExpression Id. */
  int RMAX = 49;
  /** RegularExpression Id. */
  int RMIN = 50;
  /** RegularExpression Id. */
  int R = 51;
  /** RegularExpression Id. */
  int S = 52;
  /** RegularExpression Id. */
  int SLAVE = 53;
  /** RegularExpression Id. */
  int STOCHASTIC = 54;
  /** RegularExpression Id. */
  int SYSTEM = 55;
  /** RegularExpression Id. */
  int TRUE = 56;
  /** RegularExpression Id. */
  int U = 57;
  /** RegularExpression Id. */
  int UNIFORM = 58;
  /** RegularExpression Id. */
  int W = 59;
  /** RegularExpression Id. */
  int WEIBULL = 60;
  /** RegularExpression Id. */
  int NOT = 61;
  /** RegularExpression Id. */
  int AND = 62;
  /** RegularExpression Id. */
  int OR = 63;
  /** RegularExpression Id. */
  int IMPLIES = 64;
  /** RegularExpression Id. */
  int IFF = 65;
  /** RegularExpression Id. */
  int DMINUS = 66;
  /** RegularExpression Id. */
  int RARROW = 67;
  /** RegularExpression Id. */
  int COLON = 68;
  /** RegularExpression Id. */
  int SEMICOLON = 69;
  /** RegularExpression Id. */
  int COMMA = 70;
  /** RegularExpression Id. */
  int DOTS = 71;
  /** RegularExpression Id. */
  int LPARENTH = 72;
  /** RegularExpression Id. */
  int RPARENTH = 73;
  /** RegularExpression Id. */
  int LBRACKET = 74;
  /** RegularExpression Id. */
  int RBRACKET = 75;
  /** RegularExpression Id. */
  int DLBRACKET = 76;
  /** RegularExpression Id. */
  int DRBRACKET = 77;
  /** RegularExpression Id. */
  int LBRACE = 78;
  /** RegularExpression Id. */
  int RBRACE = 79;
  /** RegularExpression Id. */
  int EQ = 80;
  /** RegularExpression Id. */
  int NE = 81;
  /** RegularExpression Id. */
  int LT = 82;
  /** RegularExpression Id. */
  int GT = 83;
  /** RegularExpression Id. */
  int DLT = 84;
  /** RegularExpression Id. */
  int DGT = 85;
  /** RegularExpression Id. */
  int LE = 86;
  /** RegularExpression Id. */
  int GE = 87;
  /** RegularExpression Id. */
  int PLUS = 88;
  /** RegularExpression Id. */
  int MINUS = 89;
  /** RegularExpression Id. */
  int TIMES = 90;
  /** RegularExpression Id. */
  int DIVIDE = 91;
  /** RegularExpression Id. */
  int PRIME = 92;
  /** RegularExpression Id. */
  int RENAME = 93;
  /** RegularExpression Id. */
  int QMARK = 94;
  /** RegularExpression Id. */
  int DQUOTE = 95;
  /** RegularExpression Id. */
  int REG_INT = 96;
  /** RegularExpression Id. */
  int REG_DOUBLE = 97;
  /** RegularExpression Id. */
  int REG_IDENTPRIME = 98;
  /** RegularExpression Id. */
  int REG_IDENT = 99;
  /** RegularExpression Id. */
  int PREPROC = 100;
  /** RegularExpression Id. */
  int LEXICAL_ERROR = 101;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<COMMENT>",
    "\"A\"",
    "\"bool\"",
    "\"clock\"",
    "\"const\"",
    "\"ctmc\"",
    "\"C\"",
    "\"distribution\"",
    "\"dirac\"",
    "\"double\"",
    "\"dtmc\"",
    "\"E\"",
    "\"endinit\"",
    "\"endinvariant\"",
    "\"endmodule\"",
    "\"endrewards\"",
    "\"endsystem\"",
    "\"erlang\"",
    "\"event\"",
    "\"exponential\"",
    "\"false\"",
    "\"formula\"",
    "\"filter\"",
    "\"func\"",
    "\"F\"",
    "\"global\"",
    "\"G\"",
    "\"init\"",
    "\"gsmp\"",
    "\"invariant\"",
    "\"I\"",
    "\"int\"",
    "\"label\"",
    "\"max\"",
    "\"mdp\"",
    "\"min\"",
    "\"module\"",
    "\"X\"",
    "\"nondeterministic\"",
    "\"Pmax\"",
    "\"Pmin\"",
    "\"P\"",
    "\"probabilistic\"",
    "\"prob\"",
    "\"pta\"",
    "\"rate\"",
    "\"rewards\"",
    "\"Rmax\"",
    "\"Rmin\"",
    "\"R\"",
    "\"S\"",
    "\"slave\"",
    "\"stochastic\"",
    "\"system\"",
    "\"true\"",
    "\"U\"",
    "\"uniform\"",
    "\"W\"",
    "\"weibull\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"=>\"",
    "\"<=>\"",
    "\"--\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"..\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"[[\"",
    "\"]]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<<\"",
    "\">>\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "\"<-\"",
    "\"?\"",
    "\"\\\"\"",
    "<REG_INT>",
    "<REG_DOUBLE>",
    "<REG_IDENTPRIME>",
    "<REG_IDENT>",
    "<PREPROC>",
    "<LEXICAL_ERROR>",
  };

}
